version: '3.6'
volumes: 
  portainer_data: {}
networks:
  # docker network create web
  web:
    external: true
services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    restart: always
    # web.lodestreams.com
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
      - default
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.web.frontend.rule=Host:traefik.localhost"
      - "traefik.web.port=8080"
      - "traefik.web.protocol=http"
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.web.frontend.rule=Host:portainer.localhost"
      - "traefik.web.port=9000"
      - "traefik.web.protocol=http"
